# Site settings
title: PaskR
description: ""
baseurl: ""
url: "http://www.paskr.fr"

author:
    email: hello@paskr.fr

# Build settings
markdown: kramdown
permalink:   /:title

paskr:
    cv:
        enabled: false
    comments:
        provider: disqus
