# Site settings
title: PaskR
description: "Développeur Web, PHP, Symfony / Scrum Master"
baseurl: ""
url: "http://www.paskr.fr"

author:
    email: hello@paskr.fr

# Build settings
markdown: kramdown
permalink:   /:title

paskr:
    cv:
        enabled: true
    comments:
        provider: disqus
